#!/usr/bin/env python3
"""
AI-Powered LinkedIn Content Generator

Uses Claude's content-generator skill with full business context:
- Company_Handbook.md (brand voice, values, personality)
- Business_Goals.md (current objectives, KPIs, targets)
- Recent Briefings (what's happening in the business)

This replaces the old template-based generator with AI-generated content.

Usage:
    python generate_linkedin_ai.py --vault AI_Employee_Vault --count 5
"""

import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime


# Content mix strategy
CONTENT_MIX = {
    "weekly": {
        "total": 5,
        "topics": [
            "Recent business achievement or milestone",
            "Insight from Company_Handbook values",
            "Progress toward Business_Goals",
            "Industry thought leadership",
            "Behind-the-scenes of AI Employee system"
        ]
    }
}


def generate_with_claude(vault_path: Path, topic: str) -> str:
    """
    Generate LinkedIn content using Claude's content-generator skill.

    Args:
        vault_path: Path to vault
        topic: Content topic/prompt

    Returns:
        Generated content string
    """
    # Create prompt for Claude
    prompt = f"""Generate a professional LinkedIn post about: {topic}

Context to use:
1. Read Company_Handbook.md for brand voice, personality, values
2. Read Business_Goals.md for current objectives and KPIs
3. Read Briefings/ for recent business achievements and milestones
4. Match the tone and personality from Company_Handbook.md

Requirements:
- Professional but authentic voice
- 1-3 paragraphs, conversational tone
- Include 1 relevant insight or lesson learned
- End with an engagement question
- Add 3-5 relevant hashtags
- 200-500 characters (LinkedIn optimal length)
- NO generic "automation/productivity" filler
- Use specific details from the business context

Output ONLY the LinkedIn post content (no markdown code blocks, no explanations).
"""

    # Use Claude Code via skill
    try:
        result = subprocess.run(
            ["claude", "skill", "content-generator", "--prompt", prompt],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=vault_path
        )

        if result.returncode == 0:
            content = result.stdout.strip()
            # Remove any markdown code blocks if present
            if content.startswith("```"):
                content = content.split("```")[1]
                if content.startswith("linkedin"):
                    content = content.split("\n", 1)[1]
                content = content.rstrip("`").strip()
            return content
        else:
            print(f"[WARNING] Claude generation failed: {result.stderr}")
            return generate_fallback_content(topic)

    except Exception as e:
        print(f"[WARNING] Error calling Claude: {e}")
        return generate_fallback_content(topic)


def generate_fallback_content(topic: str) -> str:
    """Generate fallback content if Claude is unavailable."""
    return f"""{topic}

Building something meaningful takes time, consistency, and a willingness to learn from every setback.

What's a project you're working on that matters to you?

#BuildingInPublic #Entrepreneurship #Tech
"""


def create_approval_request(content: str, vault_path: Path) -> Path:
    """Create an approval request file for LinkedIn post."""
    pending_folder = vault_path / "Pending_Approval"
    pending_folder.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"LINKEDIN_POST_{timestamp}.md"
    filepath = pending_folder / filename

    approval_content = f"""---
type: linkedin_post
action: post_to_linkedin
platform: linkedin
created: {datetime.now().isoformat()}
expires: {datetime.now().replace(hour=23, minute=59, second=59).isoformat()}
status: pending_approval
---

# LinkedIn Post

## Content

{content}

## Metadata
- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Platform:** LinkedIn
- **Character Count:** {len(content)}
- **Method:** AI-generated with business context

## Approval Required
1. Review the post content above
2. Edit this file if you want to make changes
3. Move this file to `/Approved/` to post
4. Posts automatically via Chrome automation (fast copy-paste method)

## To Reject
Move this file to `/Rejected/` folder

---
*Generated by Social Media Manager (AI-powered) - awaiting human review*
"""

    filepath.write_text(approval_content, encoding='utf-8')
    print(f"[OK] Created: {filepath.name}")
    return filepath


def generate_content_batch(vault_path: str, count: int = 5) -> int:
    """Generate a batch of AI-powered LinkedIn content."""
    vault = Path(vault_path)

    print(f"\n{'='*60}")
    print(f"AI-Powered LinkedIn Content Generator")
    print(f"{'='*60}")
    print(f"Vault: {vault}")
    print(f"Posts to generate: {count}")
    print(f"Method: Claude AI with business context")
    print(f"{'='*60}\n")

    topics = CONTENT_MIX["weekly"]["topics"]
    generated = 0

    for i in range(count):
        topic = topics[i % len(topics)]

        print(f"[{i+1}/{count}] Generating: {topic}...")

        content = generate_with_claude(vault, topic)
        filepath = create_approval_request(content, vault)

        print(f"     -> {len(content)} characters\n")
        generated += 1

    print(f"{'='*60}")
    print(f"[OK] Generated {generated} AI-powered LinkedIn posts")
    print(f"{'='*60}")
    print(f"\nNext steps:")
    print(f"1. Review the posts in /Pending_Approval/")
    print(f"2. Edit as needed")
    print(f"3. Move approved posts to /Approved/")
    print(f"4. The approval monitor will automatically publish them")
    print(f"\n")

    return generated


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate AI-powered LinkedIn content"
    )

    parser.add_argument(
        "--vault",
        default="AI_Employee_Vault",
        help="Path to Obsidian vault"
    )

    parser.add_argument(
        "--count",
        type=int,
        default=5,
        help="Number of posts to generate"
    )

    args = parser.parse_args()

    count = generate_content_batch(
        vault_path=args.vault,
        count=args.count
    )

    return 0 if count > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
