#!/usr/bin/env python3
"""
LinkedIn Manager Skill Invoker

This script allows Claude Code to invoke the LinkedIn skill.

Usage:
    python invoke.py "Post this content to LinkedIn"
    python invoke.py "Share update about AI automation"

Returns:
    JSON output with status and post details
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))


def invoke_linkedin(task: str, vault_path: str = None) -> dict:
    """
    Invoke the LinkedIn manager skill.

    Args:
        task: Content to post to LinkedIn
        vault_path: Path to Obsidian vault

    Returns:
        dict: Result with status and post details
    """
    try:
        # Determine vault path
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        # Extract content from task
        content = task

        # Remove common prefixes
        prefixes = ["post to linkedin:", "share on linkedin:", "linkedin:"]
        for prefix in prefixes:
            if content.lower().startswith(prefix):
                content = content[len(prefix):].strip()

        # Create approval file
        pending_folder = vault_path / "Pending_Approval"
        pending_folder.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"LINKEDIN_POST_{timestamp}.md"
        filepath = pending_folder / filename

        # Create post file
        post_content = f"""---
type: linkedin_post
action: post_to_linkedin
platform: linkedin
created: {datetime.now().isoformat()}
expires: {(datetime.now().replace(hour=23, minute=59, second=59)).isoformat()}
status: pending_approval
---

# LinkedIn Post

{content}

## Metadata
- **Invoked via:** Claude Code Skill tool
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Character Count:** {len(content)}

## Approval Required
1. Review the post content above
2. Edit this file if you want to make changes
3. Move this file to `/Approved/` to post
4. LinkedIn approval monitor will handle the posting

## To Reject
Move this file to `/Rejected/` folder

---
*Generated by LinkedIn Manager Skill - awaiting human review*
"""

        filepath.write_text(post_content)

        print(f"[*] LinkedIn post created: {filename}", file=sys.stderr)

        return {
            "status": "success",
            "action": "LinkedIn post created and awaiting approval",
            "file_path": str(filepath),
            "filename": filename,
            "next_steps": [
                f"Review post at: {filepath}",
                "Move to Approved/ to publish",
                "LinkedIn monitor will post automatically"
            ],
            "error": None
        }

    except Exception as e:
        print(f"[✗] Error: {e}", file=sys.stderr)
        return {
            "status": "error",
            "error": str(e),
            "action": None
        }


def main():
    """Main entry point for skill invocation."""
    parser = argparse.ArgumentParser(
        description="Invoke LinkedIn skill"
    )
    parser.add_argument(
        "content",
        help="Content to post to LinkedIn"
    )
    parser.add_argument(
        "--vault",
        help="Path to Obsidian vault",
        default=None
    )

    args = parser.parse_args()

    # Invoke LinkedIn skill
    result = invoke_linkedin(args.content, args.vault)

    # Output as JSON
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
