#!/usr/bin/env python3
"""
Twitter Manager Skill Invoker

This script allows Claude Code to invoke the Twitter skill.

Usage:
    python invoke.py "Tweet this content"
    python invoke.py "Post update about AI"

Returns:
    JSON output with status and post details
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

# Fix UTF-8 encoding on Windows
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
if sys.stderr.encoding != 'utf-8':
    sys.stderr.reconfigure(encoding='utf-8')

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))


def invoke_twitter(task: str, vault_path: str = None) -> dict:
    """
    Invoke the Twitter manager skill.

    Args:
        task: Content to post to Twitter
        vault_path: Path to Obsidian vault

    Returns:
        dict: Result with status and post details
    """
    try:
        # Determine vault path
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        # Extract content from task
        content = task

        # Remove common prefixes
        prefixes = ["tweet:", "post to twitter:", "twitter:", "share on x:", "x:"]
        for prefix in prefixes:
            if content.lower().startswith(prefix):
                content = content[len(prefix):].strip()

        # Check character limit (Twitter max 280)
        if len(content) > 280:
            content = content[:280]
            print(f"[!] Content truncated to 280 characters", file=sys.stderr)

        # Create approval file
        pending_folder = vault_path / "Pending_Approval"
        pending_folder.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"TWITTER_POST_{timestamp}.md"
        filepath = pending_folder / filename

        # Create post file
        post_content = f"""---
type: twitter_post
action: post_to_twitter
platform: twitter
created: {datetime.now().isoformat()}
expires: {(datetime.now().replace(hour=23, minute=59, second=59)).isoformat()}
status: pending_approval
---

# Tweet

{content}

## Metadata
- **Invoked via:** Claude Code Skill tool
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Character Count:** {len(content)}/280
- **Truncated:** {"Yes" if len(content) >= 280 else "No"}

## Approval Required
1. Review the tweet above
2. Edit this file if needed
3. Move to `/Approved/` to post
4. Twitter monitor will handle posting

## To Reject
Move to `/Rejected/` folder

---
*Generated by Twitter Manager Skill - awaiting human review*
"""

        filepath.write_text(post_content)

        print(f"[*] Tweet created: {filename}", file=sys.stderr)

        return {
            "status": "success",
            "action": "Tweet created and awaiting approval",
            "file_path": str(filepath),
            "filename": filename,
            "character_count": len(content),
            "next_steps": [
                f"Review tweet at: {filepath}",
                "Move to Approved/ to publish",
                "Twitter monitor will post automatically"
            ],
            "error": None
        }

    except Exception as e:
        print(f"[✗] Error: {e}", file=sys.stderr)
        return {
            "status": "error",
            "error": str(e),
            "action": None
        }


def main():
    """Main entry point for skill invocation."""
    parser = argparse.ArgumentParser(
        description="Invoke Twitter skill"
    )
    parser.add_argument(
        "content",
        help="Content to tweet"
    )
    parser.add_argument(
        "--vault",
        help="Path to Obsidian vault",
        default=None
    )

    args = parser.parse_args()

    # Invoke Twitter skill
    result = invoke_twitter(args.content, args.vault)

    # Output as JSON
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
