#!/usr/bin/env python3
"""
Daily Review Skill Invoker

This script allows Claude Code to invoke the daily-review skill.

Usage:
    python invoke.py "Generate daily plan"
    python invoke.py "Review pending tasks for today"

Returns:
    JSON output with status and plan details
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))


def invoke_daily_review(task: str, vault_path: str = None) -> dict:
    """
    Invoke the daily review skill.

    Args:
        task: Task description
        vault_path: Path to Obsidian vault

    Returns:
        dict: Result with status and plan details
    """
    try:
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        task_lower = task.lower()
        keywords = ["daily", "review", "plan", "today", "tasks", "schedule"]

        if not any(keyword in task_lower for keyword in keywords):
            return {
                "status": "error",
                "error": "Task not recognized. Use keywords like: 'daily', 'review', 'plan', 'today'"
            }

        # Import the daily review generator
        sys.path.insert(0, str(Path(__file__).parent / "scripts"))
        from generate_daily_plan import DailyReviewGenerator

        print(f"[*] Generating daily plan...", file=sys.stderr)

        generator = DailyReviewGenerator(str(vault_path))
        plan_file = generator.generate()

        # Read the plan for summary
        plan_content = plan_file.read_text()

        # Extract key sections
        lines = plan_content.split('\n')
        summary_lines = []
        for line in lines[:30]:  # First 30 lines
            if line.strip():
                summary_lines.append(line)
            if "## Action Items" in line:
                break

        summary = '\n'.join(summary_lines[:20])

        print(f"[✅] Daily plan generated: {plan_file.name}", file=sys.stderr)

        return {
            "status": "success",
            "action": "Daily plan generated",
            "file_path": str(plan_file),
            "summary": summary,
            "date": datetime.now().strftime('%Y-%m-%d'),
            "error": None
        }

    except ImportError:
        # If module not available, create simple daily plan
        return create_simple_daily_plan(vault_path)
    except Exception as e:
        print(f"[✗] Error: {e}", file=sys.stderr)
        return {
            "status": "error",
            "error": str(e),
            "action": None
        }


def create_simple_daily_plan(vault_path: Path) -> dict:
    """Create a simple daily plan if the generator is not available."""
    try:
        plans_folder = vault_path / "Plans"
        plans_folder.mkdir(parents=True, exist_ok=True)

        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"daily_{date_str}.md"
        filepath = plans_folder / filename

        # Count items in Needs_Action
        needs_action = vault_path / "Needs_Action"
        pending_count = 0
        if needs_action.exists():
            pending_count = len(list(needs_action.glob('*.md')))

        plan_content = f"""---
type: daily_plan
date: {date_str}
status: active
---

# Daily Plan - {date_str}

## Overview
Generated by Claude Code Daily Review Skill

## Pending Items
- Items in Needs_Action: {pending_count}

## Priority Tasks
1. Review and triage Needs_Action/ folder
2. Process Pending_Approval/ items
3. Check upcoming calendar events

## Focus Areas
- Email triage
- Social media scheduling
- Project deliverables

## Notes
- Created via skill invocation
- Use AI Auto-Approver for triage assistance

---
*Generated by Daily Review Skill*
"""

        filepath.write_text(plan_content)

        return {
            "status": "success",
            "action": "Daily plan created",
            "file_path": str(filepath),
            "summary": f"Daily plan for {date_str} with {pending_count} pending items",
            "error": None
        }

    except Exception as e:
        return {
            "status": "error",
            "error": str(e)
        }


def main():
    """Main entry point for skill invocation."""
    parser = argparse.ArgumentParser(
        description="Invoke daily-review skill"
    )
    parser.add_argument(
        "task",
        help="Task description"
    )
    parser.add_argument(
        "--vault",
        help="Path to Obsidian vault",
        default=None
    )

    args = parser.parse_args()

    result = invoke_daily_review(args.task, args.vault)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
