#!/usr/bin/env python3
"""
Facebook-Instagram Manager Skill Invoker

This script allows Claude Code to invoke the Facebook/Instagram skill.

Usage:
    python invoke.py facebook "Post this content"
    python invoke.py instagram "Share this photo"

Returns:
    JSON output with status and post details
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))


def invoke_facebook(task: str, vault_path: str = None) -> dict:
    """Invoke Facebook posting."""
    try:
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        content = task

        # Remove prefixes
        prefixes = ["post to facebook:", "facebook:", "share on fb:"]
        for prefix in prefixes:
            if content.lower().startswith(prefix):
                content = content[len(prefix):].strip()

        # Create approval file
        pending_folder = vault_path / "Pending_Approval"
        pending_folder.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"FACEBOOK_POST_{timestamp}.md"
        filepath = pending_folder / filename

        post_content = f"""---
type: facebook_post
action: post_to_facebook
platform: facebook
created: {datetime.now().isoformat()}
expires: {(datetime.now().replace(hour=23, minute=59, second=59)).isoformat()}
status: pending_approval
---

# Facebook Post

{content}

## Metadata
- **Invoked via:** Claude Code Skill tool
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Approval Required
Move to `/Approved/` to post

---
*Generated by Facebook-Instagram Manager Skill*
"""

        filepath.write_text(post_content)

        return {
            "status": "success",
            "action": "Facebook post created",
            "file_path": str(filepath),
            "platform": "facebook"
        }

    except Exception as e:
        return {"status": "error", "error": str(e)}


def invoke_instagram(task: str, vault_path: str = None) -> dict:
    """Invoke Instagram posting with auto-image generation."""
    try:
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        content = task

        # Remove prefixes
        prefixes = ["post to instagram:", "instagram:", "share on ig:"]
        for prefix in prefixes:
            if content.lower().startswith(prefix):
                content = content[len(prefix):].strip()

        # Create approval file
        pending_folder = vault_path / "Pending_Approval"
        pending_folder.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"INSTAGRAM_POST_{timestamp}.md"
        filepath = pending_folder / filename

        post_content = f"""---
type: instagram_post
action: post_to_instagram
platform: instagram
created: {datetime.now().isoformat()}
expires: {(datetime.now().replace(hour=23, minute=59, second=59)).isoformat()}
status: pending_approval
---

# Instagram Post

{content}

## Image Generation
- Professional 1080x1080 image will be auto-generated
- 6 color themes available
- Emojis removed from image (kept in caption)

## Metadata
- **Invoked via:** Claude Code Skill tool
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Caption Length:** {len(content)} characters

## Approval Required
Move to `/Approved/` to post (image will be generated automatically)

---
*Generated by Facebook-Instagram Manager Skill*
"""

        filepath.write_text(post_content)

        return {
            "status": "success",
            "action": "Instagram post created (image will be auto-generated)",
            "file_path": str(filepath),
            "platform": "instagram",
            "image_generation": "1080x1080 professional image"
        }

    except Exception as e:
        return {"status": "error", "error": str(e)}


def main():
    """Main entry point for skill invocation."""
    parser = argparse.ArgumentParser(
        description="Invoke Facebook/Instagram skill"
    )
    parser.add_argument(
        "platform",
        choices=["facebook", "instagram"],
        help="Platform to post to"
    )
    parser.add_argument(
        "content",
        help="Content to post"
    )
    parser.add_argument(
        "--vault",
        help="Path to Obsidian vault",
        default=None
    )

    args = parser.parse_args()

    # Invoke appropriate platform
    if args.platform == "facebook":
        result = invoke_facebook(args.content, args.vault)
    else:
        result = invoke_instagram(args.content, args.vault)

    # Output as JSON
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
